package com.example.module.entity;

import java.util.Date;

public class BidDocDownload {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.download_ID
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer downloadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.biz_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.bid_doc_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer bidDocId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.multimedia_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer multimediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.doc_layout_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer docLayoutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.doc_type
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Byte docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.is_attachment
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Byte isAttachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.creater_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Integer createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.create_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.update_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_doc_download.is_deleted
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.download_ID
     *
     * @return the value of bid_doc_download.download_ID
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getDownloadId() {
        return downloadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.download_ID
     *
     * @param downloadId the value for bid_doc_download.download_ID
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setDownloadId(Integer downloadId) {
        this.downloadId = downloadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.biz_id
     *
     * @return the value of bid_doc_download.biz_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.biz_id
     *
     * @param bizId the value for bid_doc_download.biz_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.bid_doc_id
     *
     * @return the value of bid_doc_download.bid_doc_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getBidDocId() {
        return bidDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.bid_doc_id
     *
     * @param bidDocId the value for bid_doc_download.bid_doc_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setBidDocId(Integer bidDocId) {
        this.bidDocId = bidDocId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.multimedia_id
     *
     * @return the value of bid_doc_download.multimedia_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getMultimediaId() {
        return multimediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.multimedia_id
     *
     * @param multimediaId the value for bid_doc_download.multimedia_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setMultimediaId(Integer multimediaId) {
        this.multimediaId = multimediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.doc_layout_id
     *
     * @return the value of bid_doc_download.doc_layout_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getDocLayoutId() {
        return docLayoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.doc_layout_id
     *
     * @param docLayoutId the value for bid_doc_download.doc_layout_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setDocLayoutId(Integer docLayoutId) {
        this.docLayoutId = docLayoutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.doc_type
     *
     * @return the value of bid_doc_download.doc_type
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Byte getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.doc_type
     *
     * @param docType the value for bid_doc_download.doc_type
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setDocType(Byte docType) {
        this.docType = docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.is_attachment
     *
     * @return the value of bid_doc_download.is_attachment
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Byte getIsAttachment() {
        return isAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.is_attachment
     *
     * @param isAttachment the value for bid_doc_download.is_attachment
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setIsAttachment(Byte isAttachment) {
        this.isAttachment = isAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.creater_id
     *
     * @return the value of bid_doc_download.creater_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Integer getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.creater_id
     *
     * @param createrId the value for bid_doc_download.creater_id
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setCreaterId(Integer createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.create_time
     *
     * @return the value of bid_doc_download.create_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.create_time
     *
     * @param createTime the value for bid_doc_download.create_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.update_time
     *
     * @return the value of bid_doc_download.update_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.update_time
     *
     * @param updateTime the value for bid_doc_download.update_time
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_doc_download.is_deleted
     *
     * @return the value of bid_doc_download.is_deleted
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_doc_download.is_deleted
     *
     * @param isDeleted the value for bid_doc_download.is_deleted
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}