package com.example.module.mapper;

import com.example.module.entity.BidDocDownload;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BidDocDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    int deleteByPrimaryKey(Integer downloadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    int insert(BidDocDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    int insertSelective(BidDocDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    BidDocDownload selectByPrimaryKey(Integer downloadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    int updateByPrimaryKeySelective(BidDocDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bid_doc_download
     *
     * @mbggenerated Thu Jun 14 14:33:10 CST 2018
     */
    int updateByPrimaryKey(BidDocDownload record);
}